export const ClassRoom = [
  {
    id: 1,
    feature2: false,
    heading: "Get Control Over Your Subscriptions",
    desc: "Never pay for an unwanted subscription again. Subsentry  instantly finds and tracks your subscriptions. Your concierge is there when you need them to cancel services so you don’t have to",
    // title: "Assignment Management ",
    cardTitle1: "Receiveing Alert ",
    cardTitle2: "Resource Sharing",
    img1: "/SubletImages/subscribe_12437329.png",
    img2: "/SubletImages/subscription_7261321.png",
    paragraph1:
      "Subsentry allows you to set alerts before your next payments.Exactly when you want them. Sent wherever you want",
    paragraph2: " manage all of your finances online with Subsentry ",
    path: "/Manage_subscriptions",
  },
  {
    path: "/spending-insights",
    id: 2,
    feature2: true,
    img: "/SubletImages/man1.png",
    heading: "Stay On Top Of Your Spending",
    desc: "Get an effortless breakdown of your finances to see where your money is going and how to improve. We’ll notify you of important events that need your attention so you’re never caught off guard.",
    title: "Stay On Top Of Your Spending ",
  },
  {
    path: "/Autopilot_savings",
    id: 1,
    feature2: false,
    heading: "Put Your Savings On Track with Subsentry ",
    desc: "Never pay for an unwanted subscription again. Sublet APP instantly finds and  tracks your subscriptions. Your concierge is there when you need them to cancel services so you don’t have to. ",
    // title: "Curriculum Management ",
    cardTitle1: "Payment Flexibility ",
    paragraph1: " help ensure your finances stay safe and secure",
    cardTitle2: "Support personal growth",
    paragraph2:
      "Time and resources are a constraint.we are faster, more effective in our support for growth ",
    img1: "/SubletImages/save-money_2676802.png",
    img2: "/SubletImages/carbon_chart-stepper.svg",
  },
];
